name: Morelo-GUI Build

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller psutil pyperclip image PyQt5 qrcode requests
    - name: build with pyinstaller
      run: |
        pyinstaller --onefile MRL-GUI-Wallet.py --icon=morelo.ico -c
    - name: Upload compiled binary for windows
      uses: actions/upload-artifact@v1
      with:
        name: Windows Binary
        path: dist/MRL-GUI-Wallet.exe

  build-macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller psutil pyperclip image PyQt5 qrcode requests
    - name: build with pyinstaller
      run: |
        pyinstaller --onefile MRL-GUI-Wallet.py --icon=morelo.ico -c
    - name: Upload compiled binary for macOS
      uses: actions/upload-artifact@v1
      with:
        name: MacOS Binary
        path: dist/MRL-GUI-Wallet.app

  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller psutil pyperclip image PyQt5 qrcode requests
    - name: build with pyinstaller
      run: |
        pyinstaller --onefile MRL-GUI-Wallet.py --icon=morelo.ico
    - name: Upload compiled binary for ubuntu
      uses: actions/upload-artifact@v1
      with:
        name: Ubuntu Binary
        path: dist/MRL-GUI-Wallet
